/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'primary-fixed': '#6bff8f',
        'surface-variant': '#e3e2e0',
        'on-secondary-fixed': '#1b1b1b',
        'tertiary-fixed': '#e3e2e0',
        primary: '#006e2f',
        'surface-tint': '#006e2f',
        'on-secondary-fixed-variant': '#474747',
        'tertiary-fixed-dim': '#c7c6c5',
        'surface-container-low': '#f5f3f1',
        'on-secondary-container': '#646464',
        'on-tertiary-container': '#3f403f',
        'tertiary-container': '#acacaa',
        outline: '#6d7b6c',
        'secondary-fixed': '#e2e2e2',
        tertiary: '#5e5e5d',
        'inverse-surface': '#303130',
        'on-surface': '#1b1c1b',
        'primary-fixed-dim': '#4ae176',
        'primary-container': '#22c55e',
        'secondary-fixed-dim': '#c6c6c6',
        'outline-variant': '#bccbb9',
        error: '#ba1a1a',
        'inverse-on-surface': '#f2f0ee',
        'on-primary-fixed-variant': '#005321',
        'on-primary-fixed': '#002109',
        surface: '#faf9f7',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e3e2e0',
        'on-secondary': '#ffffff',
        'on-background': '#1b1c1b',
        'secondary-container': '#e2e2e2',
        'on-primary-container': '#004b1e',
        'on-tertiary-fixed': '#1a1c1b',
        'on-tertiary-fixed-variant': '#464746',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e9e8e6',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'on-surface-variant': '#3d4a3d',
        'surface-dim': '#dbdad8',
        'surface-container': '#efeeec',
        'surface-bright': '#faf9f7',
        'inverse-primary': '#4ae176',
        background: '#faf9f7',
        secondary: '#5e5e5e',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        gutter: '20px',
        lg: '24px',
        xl: '40px',
      },
      fontFamily: {
        inter: ['Inter'],
        mono: ['JetBrains Mono'],
      },
    },
  },
  plugins: [],
};
